version: '3.7'

services:
  web:
    build: ./web
    # command: gunicorn src.wsgi:application --bind 0.0.0.0:8000
    command: python manage.py runserver_plus 0.0.0.0:8000 --cert-file cert.crt
#    command: python manage.py migrate
    volumes:
      - ./web/:/usr/src/web/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
      - ./.env.accounts
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:12.0-alpine
    hostname: postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db



volumes:
  postgres_data:

