# Generated by Django 3.0.4 on 2020-06-16 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='Title')),
                ('content_short', models.TextField(blank=True, null=True, verbose_name='Short description')),
                ('content_full', models.TextField(blank=True, null=True, verbose_name='Post text')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Published date')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Url')),
                ('image', models.ImageField(blank=True, default='post_images/no-image-available.jpg', upload_to=posts.models.article_upload_path, verbose_name='Post image')),
                ('is_published', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='post_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.SlugField(blank=True, unique=True, verbose_name='Url')),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'section',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='Author name')),
                ('comment_text', models.CharField(max_length=200, verbose_name='Comment')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Published  date')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.ArticleModel')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.Section'),
        ),
    ]
